#!/usr/bin/env bash
set -Eeuo pipefail
readonly HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
for file in entrypoint.sh bootstrap_ltx.sh install_openmontage.sh install_musetalk.sh install_chatterbox.sh run_ltx_clip.sh verify_ready_state.sh self_stop.sh arm_watchdog.sh; do
  bash -n "$HERE/$file"
  ! grep -Eq '^[[:space:]]*set[[:space:]]+-[^[:space:]]*x' "$HERE/$file"
done
python3 -c 'import pathlib, sys; compile(pathlib.Path(sys.argv[1]).read_text(), sys.argv[1], "exec")' \
  "$HERE/health_server.py"
public_line="$(grep -n "printf 'PUBLIC_HEALTH=" "$HERE/entrypoint.sh" | cut -d: -f1)"
ready_line="$(grep -n "printf 'READY" "$HERE/entrypoint.sh" | cut -d: -f1)"
[[ -n "$public_line" && -n "$ready_line" && "$public_line" -lt "$ready_line" ]]
grep -Fq 'TEST_LIMIT_SECONDS:-360' "$HERE/arm_watchdog.sh"
grep -Fq 'test_host_validated_no_models' "$HERE/bootstrap_ltx.sh"
grep -Fq 'TEST_MODE:-0' "$HERE/bootstrap_ltx.sh"
test_guard_line="$(grep -n 'TEST_MODE:-0' "$HERE/bootstrap_ltx.sh" | head -n1 | cut -d: -f1)"
download_line="$(grep -n 'stage download_ltx25_models' "$HERE/bootstrap_ltx.sh" | cut -d: -f1)"
[[ "$test_guard_line" -lt "$download_line" ]]
grep -Fq 'vae/ltx-2.5-video-vae-bf16.safetensors' "$HERE/bootstrap_ltx.sh"
grep -Fq 'model_patches/ltx-2.5-duration-head-bf16.safetensors' "$HERE/bootstrap_ltx.sh"
! grep -Fq 'uv sync --frozen' "$HERE/bootstrap_ltx.sh"
grep -Fq 'stage fetch_ltx_source' "$HERE/bootstrap_ltx.sh"
grep -Fq 'stage resolve_ltx_revision' "$HERE/bootstrap_ltx.sh"
grep -Fq 'stage sync_ltx_dependencies' "$HERE/bootstrap_ltx.sh"
grep -Fq 'LTX_SOURCE_TIMEOUT_SECONDS:-300' "$HERE/bootstrap_ltx.sh"
grep -Fq 'https://codeload.github.com/Lightricks/LTX-2/tar.gz/${LTX_REF}' "$HERE/bootstrap_ltx.sh"
grep -Fq 'LTX_SOURCE_MARKER="$LTX_ROOT/.arye-source-ref"' "$HERE/bootstrap_ltx.sh"
grep -Fq -- "-name 'LTX-2-*'" "$HERE/bootstrap_ltx.sh"
grep -Fq 'packages/ltx-pipelines' "$HERE/bootstrap_ltx.sh"
! grep -Fq 'git clone --progress' "$HERE/bootstrap_ltx.sh"
grep -Fq 'UV_SYNC_TIMEOUT_SECONDS:-1200' "$HERE/bootstrap_ltx.sh"
grep -Fq 'LTX_VERIFY_TIMEOUT_SECONDS:-60' "$HERE/bootstrap_ltx.sh"
grep -Fq 'NETWORK_RETRY_ATTEMPTS:-3' "$HERE/bootstrap_ltx.sh"
grep -Fq 'INITIAL_SETUP_MIN_FREE_GB:-200' "$HERE/bootstrap_ltx.sh"
grep -Fq 'READY_SETUP_MIN_FREE_GB:-32' "$HERE/bootstrap_ltx.sh"
grep -Fq 'model_cache_complete' "$HERE/bootstrap_ltx.sh"
grep -Fq 'MODEL_CACHE=COMPLETE MIN_FREE_GB=' "$HERE/bootstrap_ltx.sh"
grep -Fq "name '*.incomplete'" "$HERE/bootstrap_ltx.sh"
grep -Fq 'ltx-runtime.ready' "$HERE/bootstrap_ltx.sh"
grep -Fq 'openmontage-runtime.ready' "$HERE/bootstrap_ltx.sh"
grep -Fq 'rm -f "$STATE_DIR/setup.failed" "$STATE_DIR/stack.ready"' "$HERE/bootstrap_ltx.sh"
grep -Fq 'stage verify_ltx_cuda' "$HERE/bootstrap_ltx.sh"
grep -Fq 'stage verify_ltx_distilled_cli' "$HERE/bootstrap_ltx.sh"
grep -Fq 'uv run --no-sync python -c' "$HERE/bootstrap_ltx.sh"
grep -Fq 'LTX_DISTILLED_MODULE=READY' "$HERE/bootstrap_ltx.sh"
! grep -Fq 'python -m ltx_pipelines.distilled --help' "$HERE/bootstrap_ltx.sh"
grep -Fq 'stage verify_openmontage_runtime' "$HERE/bootstrap_ltx.sh"
grep -Fq 'stage install_musetalk' "$HERE/bootstrap_ltx.sh"
grep -Fq 'stage install_chatterbox' "$HERE/bootstrap_ltx.sh"
grep -Fq 'cd "$OPENMONTAGE_ROOT"' "$HERE/bootstrap_ltx.sh"
grep -Fq 'OPENMONTAGE_IMPORT=READY' "$HERE/bootstrap_ltx.sh"
! grep -Fq 'registry.discover()' "$HERE/bootstrap_ltx.sh"
grep -Fq 'LTX-2.5-22b-IC-LoRA-Pixel-Spatial-Upscaler' "$HERE/bootstrap_ltx.sh"
grep -Fq 'Width/height must divide by 32' "$HERE/run_ltx_clip.sh"
grep -Fq 'READY_STATE=VALID' "$HERE/verify_ready_state.sh"
grep -Fq 'LTX_DISTILLED_MODULE=READY' "$HERE/verify_ready_state.sh"
grep -Fq 'OPENMONTAGE_IMPORT=READY' "$HERE/verify_ready_state.sh"
grep -Fq 'MUSETALK_RUNTIME=READY' "$HERE/verify_ready_state.sh"
grep -Fq 'CHATTERBOX_HEBREW=READY' "$HERE/verify_ready_state.sh"
grep -Fq 'dicta-1.0.int8.onnx' "$HERE/install_chatterbox.sh"
grep -Fq 't3_mtl23ls_v3.safetensors' "$HERE/install_chatterbox.sh"
grep -Fq 'musetalkV15/unet.pth' "$HERE/install_musetalk.sh"
grep -Fq 'MUSETALK_MODEL_TOO_SMALL=' "$HERE/install_musetalk.sh"
grep -Fq 'from musetalk.utils.preprocessing import get_landmark_and_bbox' "$HERE/install_musetalk.sh"
grep -Fq 'MuseTalk/archive/${MUSE_REF}.tar.gz' "$HERE/install_musetalk.sh"
grep -Fq '.arye-source-ref' "$HERE/install_musetalk.sh"
! grep -Fq 'git clone --depth 1 https://github.com/TMElyralab/MuseTalk.git' "$HERE/install_musetalk.sh"
grep -Fq "tr '\\r\\000' '\\n\\n'" "$HERE/entrypoint.sh"
grep -Fq 'libgl1 libglib2.0-0 libsm6 libxext6 libxrender1' "$HERE/Dockerfile"
grep -Fq "name '*.incomplete'" "$HERE/verify_ready_state.sh"
grep -Fq 'verify_ready_state.sh' "$HERE/Dockerfile"
grep -Fq 'SETUP_RESULT=READY' "$HERE/entrypoint.sh"
grep -Fxq 'report_setup' "$HERE/entrypoint.sh"
! grep -Fq 'report_setup &' "$HERE/entrypoint.sh"
grep -Fq 'SETUP_DIAGNOSTIC_BEGIN' "$HERE/entrypoint.sh"
grep -Fq 'REDACTED_SENSITIVE_LINE' "$HERE/entrypoint.sh"
grep -Fq 'SETUP_LOG=' "$HERE/entrypoint.sh"
grep -Fq 'tee "$STATE_DIR/setup.log"' "$HERE/entrypoint.sh"
grep -Fq 'AUTO_STOP_HOLD_MAX_SECONDS:-180' "$HERE/entrypoint.sh"
grep -Fq 'ACTION=EXIT_FOR_CLEAN_RESTART' "$HERE/entrypoint.sh"
! grep -Fq 'while :; do sleep 3600; done' "$HERE/entrypoint.sh"
! grep -Eq 'printf.*CONTAINER_API_KEY|echo.*CONTAINER_API_KEY' "$HERE/self_stop.sh"
grep -Fq 'FROM ubuntu:24.04' "$HERE/Dockerfile"
printf 'PRODUCTION_BOOTSTRAP_STATIC_TESTS=PASS\n'
